// Build a /legacy/<file> URL, serving the MINIFIED variant in production and
// the readable original in development.
//
// The *.min.js / *.min.css files are generated by scripts/minify-legacy.mjs
// (run in `prebuild`) and are gitignored. `next dev` never minifies, so dev
// serves the originals — handy for debugging. NODE_ENV is statically known at
// build time, so there is no runtime cost and prod emits .min paths directly.
const USE_MIN = process.env.NODE_ENV === 'production';

/**
 * @param file  legacy filename, e.g. "script.js" or "styles.css"
 * @param version optional cache-bust value appended as ?v=... (after the name)
 */
export function legacyAsset(file: string, version?: string): string {
  const name = USE_MIN ? file.replace(/\.(js|css)$/, '.min.$1') : file;
  const q = version ? `?v=${version}` : '';
  return `/legacy/${name}${q}`;
}
